// lib/recetas/esqueletos/patologia.ts
import type { Esqueleto } from './types'

export const ESQUELETOS_PATOLOGIA: Esqueleto[] = [
  {
    id: 'pat-01-colon-irritable-comida',
    perfil: 'patologia',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',  gramos: 150 },
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',      gramos: 90  },
      { rol: 'verdura_volumen',    nombre: 'zanahoria cocida',  gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 7   },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['base', 'pre_entreno', 'tapering'],
      deportes: ['running', 'ciclismo', 'todos'],
      objetivos: ['rendimiento', 'salud'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['merluza al vapor', 'bacalao', 'pavo', 'gambas'],
      carbohidrato_base: ['patata cocida', 'pasta de arroz', 'tapioca cocida'],
      verdura_volumen: ['judías verdes bien cocidas', 'espinacas al vapor', 'calabacín bien cocido'],
    },
  },
  {
    id: 'pat-02-colon-irritable-cena',
    perfil: 'patologia',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'merluza',           gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'patata cocida',     gramos: 160 },
      { rol: 'verdura_volumen',    nombre: 'judías verdes',     gramos: 120 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 6   },
    ],
    tecnica: 'vapor',
    metadatos: {
      momentos: ['base', 'tapering'],
      deportes: ['todos'],
      objetivos: ['salud', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['bacalao desalado', 'pechuga de pollo', 'rape', 'pavo'],
      carbohidrato_base: ['arroz blanco', 'boniato cocido'],
      verdura_volumen: ['zanahoria cocida', 'espinacas al vapor', 'calabacín al vapor'],
    },
  },
  {
    id: 'pat-03-colon-irritable-desayuno',
    perfil: 'patologia',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco cocido',    gramos: 150 },
      { rol: 'fruta_complemento',  nombre: 'plátano maduro',         gramos: 100 },
      { rol: 'salsa_condimento',   nombre: 'aceite de coco virgen',  gramos: 5   },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'pre_entreno'],
      deportes: ['todos'],
      objetivos: ['salud', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'bajo',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      carbohidrato_base: ['pan blanco sin fibra tostado', 'tortitas de arroz'],
      fruta_complemento: ['naranja pelada', 'uvas', 'mandarina'],
    },
  },
  {
    id: 'pat-04-resistencia-insulina-comida',
    perfil: 'patologia',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',    gramos: 170 },
      { rol: 'verdura_volumen',    nombre: 'espinacas salteadas', gramos: 200 },
      { rol: 'carbohidrato_base',  nombre: 'lentejas cocidas',    gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',     gramos: 10  },
      { rol: 'salsa_condimento',   nombre: 'vinagre de Módena',   gramos: 10  },
    ],
    tecnica: 'salteado',
    metadatos: {
      momentos: ['base', 'post_entreno'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'salud'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['salmón', 'ternera magra', 'merluza', 'huevo'],
      verdura_volumen: ['brócoli', 'judías verdes', 'pimiento', 'coliflor'],
      carbohidrato_base: ['garbanzos', 'judías negras', 'quinoa', 'arroz integral'],
    },
  },
  {
    id: 'pat-05-resistencia-insulina-cena',
    perfil: 'patologia',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'salmón fresco',        gramos: 160 },
      { rol: 'verdura_volumen',    nombre: 'brócoli',              gramos: 200 },
      { rol: 'verdura_volumen',    nombre: 'pimiento asado',       gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',      gramos: 10  },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'salud'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['resistencia_insulina', 'dislipidemia'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['atún fresco', 'caballa', 'pechuga de pollo', 'ternera magra'],
      verdura_volumen: ['coliflor', 'espinacas', 'calabacín', 'judías verdes'],
    },
  },
  {
    id: 'pat-06-resistencia-insulina-desayuno',
    perfil: 'patologia',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'huevo entero',      gramos: 150 },
      { rol: 'lacteo_base',        nombre: 'queso fresco 0%',   gramos: 80  },
      { rol: 'verdura_volumen',    nombre: 'tomate',            gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 5   },
    ],
    tecnica: 'plancha',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'salud'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      proteina_principal: ['claras + 1 yema', 'pechuga de pavo en lonchas'],
      verdura_volumen: ['espinacas', 'pimiento', 'champiñones'],
      lacteo_base: ['yogur griego natural 0%', 'requesón'],
    },
  },
  {
    id: 'pat-07-hipotiroidismo-comida',
    perfil: 'patologia',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'atún fresco',        gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',       gramos: 85  },
      { rol: 'verdura_volumen',    nombre: 'judías verdes',      gramos: 150 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',    gramos: 8   },
      { rol: 'especias_aromaticos', nombre: 'perejil fresco',    gramos: 5   },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['base'],
      deportes: ['todos'],
      objetivos: ['salud', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['hipotiroidismo'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['bacalao', 'gambas', 'merluza', 'pechuga de pollo'],
      verdura_volumen: ['zanahoria', 'espárragos', 'pimiento', 'calabacín'],
    },
  },
  {
    id: 'pat-08-hipotiroidismo-cena',
    perfil: 'patologia',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',      gramos: 150 },
      { rol: 'verdura_volumen',    nombre: 'espárragos trigueros',  gramos: 150 },
      { rol: 'carbohidrato_base',  nombre: 'quinoa',                gramos: 60  },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',       gramos: 8   },
      { rol: 'especias_aromaticos', nombre: 'nueces troceadas',     gramos: 15  },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['salud'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['hipotiroidismo'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['pavo', 'merluza', 'salmón', 'gambas'],
      verdura_volumen: ['judías verdes', 'zanahoria', 'pimiento asado'],
      especias_aromaticos: ['semillas de sésamo', 'semillas de girasol'],
    },
  },
  {
    id: 'pat-09-dislipidemia-comida',
    perfil: 'patologia',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'salmón fresco',       gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'avena cocida',        gramos: 60  },
      { rol: 'verdura_volumen',    nombre: 'brócoli',             gramos: 180 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',     gramos: 10  },
      { rol: 'especias_aromaticos', nombre: 'ajo cocido',         gramos: 8   },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['base'],
      deportes: ['todos'],
      objetivos: ['salud'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['dislipidemia'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['caballa', 'atún fresco', 'sardinas frescas', 'trucha'],
      carbohidrato_base: ['legumbres', 'arroz integral', 'quinoa'],
      verdura_volumen: ['espinacas', 'col de Bruselas cocida', 'alcachofa cocida'],
    },
  },
  {
    id: 'pat-10-dislipidemia-cena',
    perfil: 'patologia',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'caballa al horno',     gramos: 140 },
      { rol: 'verdura_volumen',    nombre: 'espinacas salteadas',  gramos: 200 },
      { rol: 'carbohidrato_base',  nombre: 'garbanzos cocidos',    gramos: 80  },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',      gramos: 10  },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['salud'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['dislipidemia'],
      patologias_incompatibles: ['colon_irritable'],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['sardinas frescas', 'atún fresco', 'trucha', 'salmón'],
      carbohidrato_base: ['lentejas', 'judías blancas', 'quinoa'],
      verdura_volumen: ['brócoli cocido', 'alcachofa', 'judías verdes'],
    },
  },
  {
    id: 'pat-11-dislipidemia-desayuno',
    perfil: 'patologia',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'avena en copos',         gramos: 60  },
      { rol: 'lacteo_base',        nombre: 'bebida de avena',        gramos: 200 },
      { rol: 'fruta_complemento',  nombre: 'manzana',                gramos: 120 },
      { rol: 'grasa_saludable',    nombre: 'nueces',                 gramos: 20  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base'],
      deportes: ['todos'],
      objetivos: ['salud'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'bajo',
      nivel_grasa: 'medio',
      patologias_compatibles: ['dislipidemia'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      fruta_complemento: ['pera', 'frutos rojos', 'naranja'],
      grasa_saludable: ['semillas de lino molidas', 'almendras', 'semillas de chía'],
      lacteo_base: ['bebida de soja sin azúcar', 'leche semidesnatada'],
    },
  },
  {
    id: 'pat-12-multipatologia-comida',
    perfil: 'patologia',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',  gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',      gramos: 80  },
      { rol: 'verdura_volumen',    nombre: 'zanahoria cocida',  gramos: 120 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 8   },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['base'],
      deportes: ['todos'],
      objetivos: ['salud', 'perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['colon_irritable', 'resistencia_insulina', 'hipotiroidismo', 'dislipidemia'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['merluza', 'bacalao', 'pavo', 'gambas'],
      carbohidrato_base: ['patata cocida', 'boniato'],
      verdura_volumen: ['judías verdes cocidas', 'espinacas al vapor'],
    },
  },
]
