// lib/recetas/esqueletos/perdida-grasa.ts
import type { Esqueleto } from './types'

export const ESQUELETOS_PERDIDA_GRASA: Esqueleto[] = [
  {
    id: 'pg-01-desayuno-base',
    perfil: 'perdida_grasa',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'lacteo_base',          nombre: 'yogur griego natural 0%',  gramos: 150 },
      { rol: 'carbohidrato_base',    nombre: 'avena en copos',            gramos: 40  },
      { rol: 'fruta_complemento',    nombre: 'frutos rojos',              gramos: 80  },
      { rol: 'proteina_secundaria',  nombre: 'proteína en polvo sabor natural', gramos: 20 },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      lacteo_base: ['kéfir natural', 'yogur de cabra', 'queso fresco batido 0%'],
      carbohidrato_base: ['copos de centeno', 'muesli sin azúcar', 'granola casera'],
      fruta_complemento: ['arándanos', 'frambuesas', 'mango', 'kiwi', 'plátano'],
      proteina_secundaria: ['huevo cocido', 'requesón', 'clara de huevo cocida'],
    },
  },
  {
    id: 'pg-02-desayuno-dia-entreno',
    perfil: 'perdida_grasa',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'pan de centeno',    gramos: 80  },
      { rol: 'proteina_principal', nombre: 'huevo entero',      gramos: 120 },
      { rol: 'fruta_complemento',  nombre: 'plátano',           gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 5   },
    ],
    tecnica: 'plancha',
    metadatos: {
      momentos: ['entreno', 'base'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      carbohidrato_base: ['pan de espelta', 'tostada integral', 'tortita de arroz'],
      proteina_principal: ['pechuga de pavo en lonchas', 'atún al natural', 'requesón'],
      fruta_complemento: ['naranja', 'manzana', 'kiwi'],
    },
  },
  {
    id: 'pg-03-comida-base',
    perfil: 'perdida_grasa',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',  gramos: 150 },
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',      gramos: 70  },
      { rol: 'verdura_volumen',    nombre: 'brócoli',           gramos: 180 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 8   },
      { rol: 'salsa_condimento',   nombre: 'limón',             gramos: 20  },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['base', 'deficit'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'hipotiroidismo', 'resistencia_insulina'],
      patologias_incompatibles: ['colon_irritable'],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['merluza', 'pavo', 'atún fresco', 'bacalao', 'gambas'],
      carbohidrato_base: ['pasta integral', 'quinoa', 'boniato', 'patata'],
      verdura_volumen: ['judías verdes', 'espinacas', 'calabacín', 'pimiento', 'zanahoria'],
      salsa_condimento: ['vinagre de Módena', 'mostaza suave', 'hierbas provenzales'],
    },
  },
  {
    id: 'pg-04-comida-dia-entreno',
    perfil: 'perdida_grasa',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',  gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'pasta integral',    gramos: 85  },
      { rol: 'verdura_volumen',    nombre: 'calabacín',         gramos: 130 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 10  },
      { rol: 'salsa_condimento',   nombre: 'tomate triturado',  gramos: 60  },
    ],
    tecnica: 'salteado',
    metadatos: {
      momentos: ['entreno', 'post_entreno'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'rendimiento'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['mediodia', 'tarde'],
    },
    sustituciones: {
      proteina_principal: ['pavo picado', 'ternera magra', 'atún fresco'],
      carbohidrato_base: ['macarrones integrales', 'espaguetis', 'arroz', 'cuscús'],
      verdura_volumen: ['pimiento rojo', 'berenjena', 'espinacas', 'champiñones'],
      salsa_condimento: ['sofrito casero', 'pisto ligero', 'salsa de tomate y albahaca'],
    },
  },
  {
    id: 'pg-05-comida-dia-descanso',
    perfil: 'perdida_grasa',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'merluza',            gramos: 180 },
      { rol: 'verdura_volumen',    nombre: 'espinacas',          gramos: 200 },
      { rol: 'carbohidrato_base',  nombre: 'patata',             gramos: 120 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',    gramos: 8   },
    ],
    tecnica: 'vapor',
    metadatos: {
      momentos: ['descanso', 'deficit'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'dislipidemia', 'resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['bacalao', 'lubina', 'dorada al horno', 'rape', 'pechuga de pollo'],
      verdura_volumen: ['acelgas', 'judías verdes', 'zanahoria cocida', 'calabacín'],
      carbohidrato_base: ['boniato', 'arroz blanco', 'quinoa'],
    },
  },
  {
    id: 'pg-06-cena-base',
    perfil: 'perdida_grasa',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',  gramos: 140 },
      { rol: 'verdura_volumen',    nombre: 'calabacín',         gramos: 200 },
      { rol: 'verdura_volumen',    nombre: 'tomate',            gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 8   },
      { rol: 'especias_aromaticos', nombre: 'hierbas provenzales', gramos: 2 },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['base', 'deficit', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'resistencia_insulina', 'dislipidemia'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['pavo', 'merluza', 'gambas', 'sepia', 'rape'],
      verdura_volumen: ['berenjena', 'pimiento', 'cebolla', 'champiñones', 'judías verdes'],
      especias_aromaticos: ['tomillo', 'romero', 'orégano', 'ajo en polvo'],
    },
  },
  {
    id: 'pg-07-cena-post-entreno-tarde',
    perfil: 'perdida_grasa',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pavo',   gramos: 150 },
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',      gramos: 60  },
      { rol: 'verdura_volumen',    nombre: 'judías verdes',     gramos: 150 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 7   },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['post_entreno', 'entreno'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['pollo', 'merluza', 'atún fresco', 'salmón'],
      carbohidrato_base: ['pasta', 'boniato', 'quinoa'],
      verdura_volumen: ['espinacas', 'brócoli', 'calabacín', 'zanahoria'],
    },
  },
  {
    id: 'pg-08-cena-dia-descanso',
    perfil: 'perdida_grasa',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'huevo entero',      gramos: 150 },
      { rol: 'verdura_volumen',    nombre: 'espinacas',         gramos: 200 },
      { rol: 'verdura_volumen',    nombre: 'tomate cherry',     gramos: 80  },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 8   },
    ],
    tecnica: 'plancha',
    metadatos: {
      momentos: ['descanso', 'deficit'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['ninguna', 'resistencia_insulina'],
      patologias_incompatibles: ['dislipidemia'],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['clara de huevo', 'tofu firme', 'pechuga de pollo', 'queso fresco 0%'],
      verdura_volumen: ['acelgas', 'pimiento asado', 'berenjena', 'calabacín'],
    },
  },
  {
    id: 'pg-09-merienda-activa',
    perfil: 'perdida_grasa',
    tipoPlato: 'Merienda',
    ingredientes: [
      { rol: 'lacteo_base',       nombre: 'yogur griego natural 0%', gramos: 150 },
      { rol: 'fruta_complemento', nombre: 'frutos rojos',            gramos: 80  },
      { rol: 'grasa_saludable',   nombre: 'nueces',                  gramos: 15  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['ninguna', 'resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['tarde'],
    },
    sustituciones: {
      lacteo_base: ['kéfir', 'queso fresco batido', 'requesón'],
      fruta_complemento: ['arándanos', 'kiwi', 'manzana', 'melocotón'],
      grasa_saludable: ['almendras', 'anacardos', 'semillas de chía'],
    },
  },
  {
    id: 'pg-10-merienda-pre-entreno',
    perfil: 'perdida_grasa',
    tipoPlato: 'Merienda',
    ingredientes: [
      { rol: 'fruta_complemento',  nombre: 'plátano',          gramos: 100 },
      { rol: 'carbohidrato_base',  nombre: 'tortita de arroz', gramos: 20  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['pre_entreno', 'entreno'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'bajo',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana', 'tarde'],
    },
    sustituciones: {
      fruta_complemento: ['dátil', 'manzana', 'naranja', 'uvas'],
      carbohidrato_base: ['pan blanco', 'galleta de avena casera'],
    },
  },
  {
    id: 'pg-11-merienda-post-entreno',
    perfil: 'perdida_grasa',
    tipoPlato: 'Merienda',
    ingredientes: [
      { rol: 'proteina_secundaria', nombre: 'proteína en polvo',  gramos: 25  },
      { rol: 'lacteo_base',         nombre: 'leche semidesnatada', gramos: 200 },
      { rol: 'fruta_complemento',   nombre: 'plátano',            gramos: 80  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['post_entreno'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa', 'rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['manana', 'tarde'],
    },
    sustituciones: {
      lacteo_base: ['bebida de avena', 'leche de almendra sin azúcar'],
      fruta_complemento: ['frutos rojos', 'mango', 'melocotón'],
    },
  },
  {
    id: 'pg-12-snack-saciante',
    perfil: 'perdida_grasa',
    tipoPlato: 'Snack',
    ingredientes: [
      { rol: 'grasa_saludable',    nombre: 'almendras',               gramos: 25  },
      { rol: 'proteina_secundaria', nombre: 'queso fresco en porciones', gramos: 50 },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'medio',
      nivel_grasa: 'alto',
      patologias_compatibles: ['ninguna', 'resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: false,
      timing_ideal: ['manana', 'tarde'],
    },
    sustituciones: {
      grasa_saludable: ['nueces', 'anacardos', 'pistachos sin sal'],
      proteina_secundaria: ['jamón york', 'pavo en lonchas', 'atún al natural'],
    },
  },
  {
    id: 'pg-13-snack-dulce-fit',
    perfil: 'perdida_grasa',
    tipoPlato: 'Snack',
    ingredientes: [
      { rol: 'fruta_complemento', nombre: 'manzana',                 gramos: 150 },
      { rol: 'lacteo_base',       nombre: 'yogur griego natural 0%', gramos: 80  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'descanso'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'bajo',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'hipotiroidismo'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: false,
      timing_ideal: ['tarde', 'manana'],
    },
    sustituciones: {
      fruta_complemento: ['pera', 'melocotón', 'mandarina', 'kiwi'],
      lacteo_base: ['requesón', 'kéfir natural'],
    },
  },
  {
    id: 'pg-14-almuerzo-media-manana',
    perfil: 'perdida_grasa',
    tipoPlato: 'Almuerzo',
    ingredientes: [
      { rol: 'fruta_complemento',   nombre: 'naranja',         gramos: 150 },
      { rol: 'proteina_secundaria', nombre: 'jamón york bajo en sal', gramos: 40 },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'deficit'],
      deportes: ['todos'],
      objetivos: ['perdida_grasa'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'bajo',
      nivel_proteina: 'bajo',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'dislipidemia', 'resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: false,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      fruta_complemento: ['manzana', 'pera', 'mandarina', 'kiwi'],
      proteina_secundaria: ['pavo en lonchas', 'atún al natural', 'requesón'],
    },
  },
]
