// lib/recetas/esqueletos/rendimiento.ts
import type { Esqueleto } from './types'

export const ESQUELETOS_RENDIMIENTO: Esqueleto[] = [
  {
    id: 'rd-01-desayuno-base-entreno',
    perfil: 'rendimiento',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'avena en copos',         gramos: 70  },
      { rol: 'lacteo_base',        nombre: 'leche semidesnatada',    gramos: 200 },
      { rol: 'fruta_complemento',  nombre: 'plátano',                gramos: 100 },
      { rol: 'proteina_secundaria', nombre: 'proteína en polvo',     gramos: 25  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['base', 'entreno'],
      deportes: ['running', 'ciclismo', 'hyrox', 'endurance', 'todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      carbohidrato_base: ['copos de centeno', 'pan de espelta tostado', 'arroz cocido'],
      lacteo_base: ['leche entera', 'bebida de avena', 'kéfir'],
      fruta_complemento: ['dátiles', 'mango', 'frutos rojos', 'naranja'],
    },
  },
  {
    id: 'rd-02-desayuno-pre-competicion',
    perfil: 'rendimiento',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',       gramos: 90  },
      { rol: 'proteina_principal', nombre: 'pechuga de pavo',    gramos: 80  },
      { rol: 'salsa_condimento',   nombre: 'mermelada de fresa', gramos: 20  },
    ],
    tecnica: 'plancha',
    metadatos: {
      momentos: ['tapering', 'pre_entreno'],
      deportes: ['running', 'ciclismo', 'triathlon', 'endurance'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'medio',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      carbohidrato_base: ['pan blanco tostado', 'tortita de arroz', 'plátano + avena'],
      proteina_principal: ['pechuga de pollo', 'huevo cocido', 'atún al natural'],
      salsa_condimento: ['miel', 'compota de manzana sin azúcar añadido'],
    },
  },
  {
    id: 'rd-03-desayuno-tapering',
    perfil: 'rendimiento',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'pan blanco',      gramos: 100 },
      { rol: 'proteina_principal', nombre: 'pechuga de pavo', gramos: 70  },
      { rol: 'fruta_complemento',  nombre: 'plátano',         gramos: 120 },
      { rol: 'salsa_condimento',   nombre: 'miel',            gramos: 15  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['tapering'],
      deportes: ['running', 'ciclismo', 'endurance', 'todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'medio',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      carbohidrato_base: ['arroz blanco cocido', 'tortitas de arroz', 'cereales sin fibra'],
      proteina_principal: ['jamón york', 'queso fresco', 'atún al natural'],
    },
  },
  {
    id: 'rd-04-desayuno-post-entreno-duro',
    perfil: 'rendimiento',
    tipoPlato: 'Desayuno',
    ingredientes: [
      { rol: 'proteina_principal',  nombre: 'huevo entero',      gramos: 150 },
      { rol: 'carbohidrato_base',   nombre: 'pan de espelta',    gramos: 80  },
      { rol: 'fruta_complemento',   nombre: 'zumo de naranja',   gramos: 200 },
      { rol: 'grasa_saludable',     nombre: 'aceite de oliva',   gramos: 5   },
    ],
    tecnica: 'plancha',
    metadatos: {
      momentos: ['post_entreno', 'recuperacion'],
      deportes: ['todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana'],
    },
    sustituciones: {
      proteina_principal: ['claras de huevo + 1 yema', 'pechuga de pavo', 'requesón'],
      carbohidrato_base: ['avena', 'tostada integral', 'arroz cocido'],
    },
  },
  {
    id: 'rd-05-comida-pre-entreno',
    perfil: 'rendimiento',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',       gramos: 95  },
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',   gramos: 130 },
      { rol: 'verdura_volumen',    nombre: 'calabacín',          gramos: 100 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',    gramos: 6   },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['pre_entreno', 'tapering'],
      deportes: ['running', 'ciclismo', 'hyrox', 'endurance', 'fuerza'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'medio',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable', 'resistencia_insulina'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      carbohidrato_base: ['pasta blanca', 'patata cocida', 'boniato', 'cuscús'],
      proteina_principal: ['pechuga de pavo', 'merluza', 'atún fresco', 'bacalao'],
      verdura_volumen: ['zanahoria cocida', 'judías verdes', 'espinacas salteadas'],
    },
  },
  {
    id: 'rd-06-comida-tapering',
    perfil: 'rendimiento',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',      gramos: 110 },
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',  gramos: 125 },
      { rol: 'verdura_volumen',    nombre: 'zanahoria cocida',  gramos: 80  },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 5   },
    ],
    tecnica: 'vapor',
    metadatos: {
      momentos: ['tapering'],
      deportes: ['running', 'ciclismo', 'triathlon', 'endurance'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'medio',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      carbohidrato_base: ['pasta blanca', 'patata cocida', 'boniato'],
      proteina_principal: ['merluza al vapor', 'pavo', 'bacalao desalado'],
      verdura_volumen: ['judías verdes cocidas', 'espinacas al vapor', 'calabacín al vapor'],
    },
  },
  {
    id: 'rd-07-comida-carga-cho',
    perfil: 'rendimiento',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'pasta blanca',      gramos: 130 },
      { rol: 'proteina_principal', nombre: 'pechuga de pavo',   gramos: 110 },
      { rol: 'salsa_condimento',   nombre: 'tomate triturado',  gramos: 80  },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 5   },
    ],
    tecnica: 'guisado',
    metadatos: {
      momentos: ['tapering', 'carga_cho'],
      deportes: ['running', 'ciclismo', 'triathlon', 'endurance'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'medio',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: ['colon_irritable', 'resistencia_insulina'],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      carbohidrato_base: ['macarrones', 'arroz blanco', 'espaguetis', 'gnocchi de patata'],
      proteina_principal: ['pechuga de pollo', 'atún al natural'],
      salsa_condimento: ['sofrito casero suave', 'salsa de tomate y albahaca'],
    },
  },
  {
    id: 'rd-08-comida-base-equilibrada',
    perfil: 'rendimiento',
    tipoPlato: 'Comida',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'salmón fresco',      gramos: 150 },
      { rol: 'carbohidrato_base',  nombre: 'quinoa',             gramos: 75  },
      { rol: 'verdura_volumen',    nombre: 'espinacas salteadas', gramos: 150 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',    gramos: 10  },
      { rol: 'salsa_condimento',   nombre: 'limón',              gramos: 20  },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['base', 'recuperacion'],
      deportes: ['todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['ninguna', 'dislipidemia', 'hipotiroidismo'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['mediodia'],
    },
    sustituciones: {
      proteina_principal: ['atún fresco', 'lubina', 'dorada', 'bacalao'],
      carbohidrato_base: ['arroz integral', 'boniato', 'lentejas'],
      verdura_volumen: ['brócoli', 'judías verdes', 'pimiento asado'],
    },
  },
  {
    id: 'rd-09-cena-post-entreno',
    perfil: 'rendimiento',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'pechuga de pollo',   gramos: 170 },
      { rol: 'carbohidrato_base',  nombre: 'arroz blanco',       gramos: 75  },
      { rol: 'verdura_volumen',    nombre: 'judías verdes',      gramos: 150 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',    gramos: 8   },
    ],
    tecnica: 'plancha + vapor',
    metadatos: {
      momentos: ['post_entreno', 'recuperacion'],
      deportes: ['todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['pavo', 'merluza', 'huevo + claras', 'ternera magra'],
      carbohidrato_base: ['pasta', 'boniato', 'quinoa'],
      verdura_volumen: ['espinacas', 'brócoli', 'calabacín'],
    },
  },
  {
    id: 'rd-10-cena-tapering',
    perfil: 'rendimiento',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'merluza',           gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'patata cocida',     gramos: 180 },
      { rol: 'verdura_volumen',    nombre: 'zanahoria cocida',  gramos: 80  },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 5   },
    ],
    tecnica: 'vapor',
    metadatos: {
      momentos: ['tapering'],
      deportes: ['running', 'ciclismo', 'endurance', 'todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'medio',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['bacalao', 'lubina', 'pechuga de pollo', 'rape'],
      carbohidrato_base: ['arroz blanco', 'boniato', 'pasta blanca'],
      verdura_volumen: ['judías verdes', 'espinacas al vapor'],
    },
  },
  {
    id: 'rd-11-cena-recuperacion',
    perfil: 'rendimiento',
    tipoPlato: 'Cena',
    ingredientes: [
      { rol: 'proteina_principal', nombre: 'salmón fresco',     gramos: 160 },
      { rol: 'carbohidrato_base',  nombre: 'arroz integral',    gramos: 65  },
      { rol: 'verdura_volumen',    nombre: 'espinacas',         gramos: 150 },
      { rol: 'grasa_saludable',    nombre: 'aceite de oliva',   gramos: 10  },
      { rol: 'especias_aromaticos', nombre: 'cúrcuma + pimienta negra', gramos: 2 },
    ],
    tecnica: 'horno',
    metadatos: {
      momentos: ['recuperacion', 'post_entreno'],
      deportes: ['todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'media',
      nivel_carbohidrato: 'medio',
      nivel_proteina: 'alto',
      nivel_grasa: 'medio',
      patologias_compatibles: ['ninguna', 'dislipidemia'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['noche'],
    },
    sustituciones: {
      proteina_principal: ['atún fresco', 'caballa', 'sardinas frescas', 'trucha'],
      carbohidrato_base: ['quinoa', 'boniato', 'lentejas rojas'],
      verdura_volumen: ['brócoli', 'pimiento asado', 'judías verdes'],
    },
  },
  {
    id: 'rd-12-merienda-pre-entreno-corta',
    perfil: 'rendimiento',
    tipoPlato: 'Merienda',
    ingredientes: [
      { rol: 'fruta_complemento', nombre: 'plátano',         gramos: 100 },
      { rol: 'lacteo_base',       nombre: 'yogur natural 0%', gramos: 125 },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['pre_entreno'],
      deportes: ['todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'bajo',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: [],
      fodmaps: 'bajos',
      adaptable_gramos: true,
      timing_ideal: ['manana', 'tarde'],
    },
    sustituciones: {
      fruta_complemento: ['dátiles', 'uvas', 'higos', 'naranja'],
      lacteo_base: ['bebida de avena', 'kéfir'],
    },
  },
  {
    id: 'rd-13-merienda-post-entreno',
    perfil: 'rendimiento',
    tipoPlato: 'Merienda',
    ingredientes: [
      { rol: 'proteina_secundaria', nombre: 'proteína en polvo',   gramos: 30  },
      { rol: 'lacteo_base',         nombre: 'leche semidesnatada', gramos: 250 },
      { rol: 'fruta_complemento',   nombre: 'plátano',             gramos: 100 },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['post_entreno'],
      deportes: ['todos'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'alto',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna'],
      patologias_incompatibles: [],
      fodmaps: 'medios',
      adaptable_gramos: true,
      timing_ideal: ['manana', 'tarde'],
    },
    sustituciones: {
      lacteo_base: ['leche de almendra enriquecida', 'leche de avena'],
      fruta_complemento: ['mango', 'dátiles', 'frutos rojos'],
    },
  },
  {
    id: 'rd-14-snack-carga-cho',
    perfil: 'rendimiento',
    tipoPlato: 'Snack',
    ingredientes: [
      { rol: 'carbohidrato_base',  nombre: 'plátano',         gramos: 120 },
      { rol: 'carbohidrato_base',  nombre: 'dátiles medjoul', gramos: 30  },
    ],
    tecnica: 'crudo',
    metadatos: {
      momentos: ['tapering', 'carga_cho', 'pre_entreno'],
      deportes: ['running', 'ciclismo', 'endurance'],
      objetivos: ['rendimiento'],
      digestibilidad: 'alta',
      nivel_carbohidrato: 'alto',
      nivel_proteina: 'bajo',
      nivel_grasa: 'bajo',
      patologias_compatibles: ['ninguna', 'colon_irritable'],
      patologias_incompatibles: ['resistencia_insulina'],
      fodmaps: 'bajos',
      adaptable_gramos: false,
      timing_ideal: ['manana', 'tarde'],
    },
    sustituciones: {
      carbohidrato_base: ['tortitas de arroz con miel', 'compota de manzana', 'uvas pasas'],
    },
  },
]
